meta_product_name: "OddRecipe"
meta_title: "OddRecipe - Make your life easier - cook with OddRecipe"
meta_description: "Connecting the app with OddBox subscription company that saves fruit and veg from being thrown away."
meta_image: "favicon.ico.png" # should exist in `app/assets/images/`
